### ISSUE TITLE
AE Network looses parts without loosing its channels

### ISSUE THREAD

**Issue by ChrisLua** [GTNewHorizons/GT-New-Horizons-Modpack#10029]
### Your GTNH Discord Username

ChrisLua

### Your Pack Version

2.1.2.3qf

### Your Server

private dedicated server with friends

### Type of Server

Vanilla Forge

### Your Expectation

Hello.
my base on 2.1.2.1 was fully functional. No issues with AE.
Updated to 2.1.2.3qf and imidiatly noticed this issue i'm goint to report here.
- no Backbone cables. i just updated, and noticed that the 2.1.2.1 AE setup, no longer behaves like before.
- large dense energy cells added to all subnets. (increased number to check if the error persists)
- moves back to 2.1.2.1 error did not happen for 8 hours. updated back to 2.1.2.3qf error happend in the first 30min

### The Reality

My AE Network looses components, while fully connected to them.
I've witnessed some issues, i'll explain it on this one:
Loged in, everything looks fine. 
Gone afk for a coffee, come back 15min later. 
Multiple items missing in ME, like 350k iron, platin, stuff, which is stored on the drives.

My 32 Drives here hold allmost all items, except a few barrels.
![drive_channels](https://user-images.githubusercontent.com/43572989/160064218-65695ea5-3154-475a-ae3c-71faf7dac41c.png)
As you can see, they're all connected, and running.
![network_showing_drives](https://user-images.githubusercontent.com/43572989/160064305-a4a2f4e1-0aa0-4a47-9c9a-5075b9be8122.png)
the subnet they are connected to, shows them aswell.
<img width="444" alt="tunnel_network" src="https://user-images.githubusercontent.com/43572989/160064366-c56a9058-efa7-401c-8da0-3f82c9a3a8c6.PNG">
The tunnel Network, is fully powered.

<img width="939" alt="network_at_terminal" src="https://user-images.githubusercontent.com/43572989/160064740-0b6f0526-3747-4b0f-b8d9-73bb842dc585.PNG">
all 32 drives show, here where i enter the terminal.

One Drive looks offline, but still has a channel, even noticed by the network.
![grafik](https://user-images.githubusercontent.com/43572989/160064967-b481a059-84ab-42f3-a3db-bfb457ed5c38.png)

With this issue my storage looks like this:
<img width="330" alt="terminal_view_while_ghost_drives" src="https://user-images.githubusercontent.com/43572989/160064762-9945874c-8213-4382-b380-0d59c7a5ee39.PNG">

<img width="1357" alt="plug_cycle" src="https://user-images.githubusercontent.com/43572989/160065297-ccaa56df-9426-4a2c-9d74-f74780ec8cca.PNG">
no i plug-cycle here

drive back up again, no channel change, anything is the same, except the drive is not black anymore
<img width="1190" alt="back_up_same_same_but_diffrent" src="https://user-images.githubusercontent.com/43572989/160065416-e41947e5-9dc6-4200-af2f-0594180c8e5d.PNG">

<img width="339" alt="terminal_view_after" src="https://user-images.githubusercontent.com/43572989/160065627-5d63c6fe-bf54-4594-8298-e77ed52763ae.PNG">
notice something wierd? we did expect that 10 items show, up, because this blacked out drive only contains 10 disk storing 1 item each. But suddenly much more items which where hidden before are now visible.

<img width="355" alt="network_after" src="https://user-images.githubusercontent.com/43572989/160065925-073c1c31-16b7-4292-b8ad-f24d0feadec4.PNG">
This is how, the network looks like after the plug-cycle.
Anthing looks the same...

This issue, happens without interaction. i can just stand around in my base (no other player on the server currently) and after some time, the drives are hidden again.

### Your Proposal

idk? FInd out what changed in that update?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
Do you have quantum bridges in the network?

**Comment by ChrisLua** [comment]
yes. one. Its part of the Purple Network. 
Solarpower -> EUTunnel -> Purple p2p Tunnel - Tunnel Net -> Purple p2p Tunnel -> Purple Controller Block

**Comment by repo-alt** [comment]
If you can reproduce that issue w/o quantum ring that would be very interesting. So far I think it is related to the QR, but if I'm wrong, it would require investigating different stuff

**Comment by Peybol90** [comment]
Hi there! I'm experiencing something like this, if not the same issue. We're 3 friends on a server using AE2 (without Quantum Ring) and weird things are happening since the last update. It seems that the channels are not on the same network but we've configured them as only one network in the past.

The result is that it's impossible to use AE2, all items, fluids and their dependences are gone. It could be what ChrisLua said: dense cables are making new subnetworks somehow.

Any ideas to deal with it?

**Comment by minecraft7771** [comment]
I had this issue as well, someone suggested me to make my drives a subnetwork and connect it via storage bus - interface coupling. Using this workaround fixes the issue for me.

**Comment by repo-alt** [comment]
If that actually helps that would be very useful information indeed.

**Comment by ChrisLua** [comment]
> I had this issue as well, someone suggested me to make my drives a subnetwork and connect it via storage bus - interface coupling. Using this workaround fixes the issue for me.

May you explain how to do it? or link to any source discribing what you did?

**Comment by minecraft7771** [comment]
> > I had this issue as well, someone suggested me to make my drives a subnetwork and connect it via storage bus - interface coupling. Using this workaround fixes the issue for me.
> 
> May you explain how to do it? or link to any source discribing what you did?

I just need to make your drives a seperate network with an interface. on the interface you place a storage bus coming from your original main network, the network can access all items and store new items via the interface-storage bus coupling. See attached image for a visual guide.
![image](https://user-images.githubusercontent.com/13762078/160250624-038bf877-5d06-4007-ba00-083dc6f26f14.png)

**Comment by GTNHAfx237v7** [comment]
Aren’t we all advised not to do this due to performance reasons? However as a temporary solution that seems OK.

**Comment by boubou19** [comment]
if you don't abuse of this it's ok.

**Comment by repo-alt** [comment]
One level of nesting, like on the picture does not affect performance much (if any). It may become problematic when people use many levels of nesting trying to avoid using a controller in a storage subnetwork.

**Comment by ChrisLua** [comment]
But... will we fix this issue then?
I mean ok, this seam to work for now. But there is some issue, will we fix it?

What do we need to generate more info to let someone fix it?

**Comment by ChrisLua** [comment]
Like above mentioned, connecting the Drive-Subnet via storage Bus, does suppress the issue.
But can we please keep trying to fix the issue?

**Comment by repo-alt** [comment]
Please try this: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10058#issuecomment-1082314978

**Comment by Neakas** [comment]
Just for completeness sake and to Help the Author in not thinking he is going insane (i sure though i was): I have the EXACT same problem. Random "Loss of Items" from Storage Drives. Unplugging and Replugging fixes it. Only occours when i create a Network update ie. Placing a new Interface or the like. i DO NOT yet have a Quantum Bridge. Just Lots of Subnets. All my Storage Drives are on 1 Subnet (16 Drives in Total)

**Comment by repo-alt** [comment]
Yes, the bug is not (only) in quantum bridges but also in p2p. Buggy functionality is disabled in the latest Jenkins build (in config).

**Comment by Neakas** [comment]
ill try that right now! Thank you!

**Comment by Neakas** [comment]
> ill try that right now! Thank you!

well i cant speak for the Author, but my problem is fixed! Thank you very Much! This was driving me crazy :D

**Comment by ChrisLua** [comment]
> Please try this: [#10058 (comment)](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10058#issuecomment-1082314978)

This seems to fix the issue.
Server and clientside mod updated.
I'll report back if the error reoccours.

Thank you!

**Comment by GTNHAfx237v7** [comment]
Short update: breaking the security terminal seems to fix everything, However then you obviously can’t use the wireless terminal.

**Comment by repo-alt** [comment]
tbh I consider disabling AE security (except for wireless), because the feature is broken by design, I just had no free time recently

**Comment by GTNH-Afx237v7** [comment]
No rush, I am still not 100% sure about the circumstances that lead to this issue and if the security terminal is the answer. Let’s see what further testing brings.

**Comment by chochem** [comment]
does anybody still have problems or can we close this?

**Comment by ChrisLua** [comment]
When said suggestions from above are in dev now, it can be closed i guess.
i'm still on 3qf with said changes, and the issue has not been around since.
