### ISSUE TITLE
Control cover can break the void miner logic

### ISSUE THREAD

**Issue by Choucousse** [GTNewHorizons/GT-New-Horizons-Modpack#10205]
### Your GTNH Discord Username

Choucousse#0605

### Your Pack Version

2.1.2.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

Void miner T1 should create ores 

### The Reality

Void miner T1 doesn't create ores (it even uses xenon for nothing)

### Your Proposal

Fix. Probably the same problem the TF and ross128b had.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNHAfx237v7** [comment]
Any logs? There was something about an empty dropmap iirc. Should however be fixed in later versions, maybe try updating?

**Comment by boubou19** [comment]
he can't he's on Delta

**Comment by GTNHAfx237v7** [comment]
Guess delta needs an update then? ;)
You could try setting up the VM without any covers, start it and see if it outputs ores. If yes, disable and then install covers without breaking the controller. Worked for me and some others as well.

**Comment by Choucousse** [comment]
So, i removed the covers (maintenance and machine covers), tried starting it but no ores were generated.
I broke the controller and placed it without any covers on it, it works. It still works if i add covers after it started working.
It only bugs if i place the controller with covers already installed.
Thanks for the infos !

**Comment by boubou19** [comment]
i don't see a PR fixing that on BW, so must be an issue still in dev. We need to investigate

**Comment by combusterf** [comment]
It also stops working (using power and not producing any ores) if you install covers sometime between building the multiblock and it being properly operational.
