### ISSUE TITLE
Platinum Bee does not produce correct combs

### ISSUE THREAD

**Issue by MrWye** [GTNewHorizons/GT-New-Horizons-Modpack#10833]
### Your GTNH Discord Username

MrWye

### Your Pack Version

2.1.2.0

### Your Server

Epsilon

### Your Expectation

Platinum Bee suppose to produce Slag, Platinum and Irridium combs, latter being specialty, assuming conditions are met (hot, arid)

### The Reality

Instead it produces Slag, Platinum and Tungsten
https://prnt.sc/UsHv_Wcoub3M
Beealizer - https://prnt.sc/VPDUPvGDJ_G0

### Your Proposal

Assuming beealizer data is correct, remove Tungsten and add Irridium

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Duplicate of #9161

**Comment by leagris** [comment]
Why is it marked duplicate of a closed solved issue?

What is it tagged `bugMinor` when the issue prevents use of a feature as intended?

Why is it closed as not planned ?

Dismissing an issue without explanation does not sound right at all.

**Comment by xSkewer** [comment]
This issue might be separate from #9161 since that one claims that bees work as intended. Also, the fix for that issue was apparently dropped on officials last year, and this issue was found on officials recently.

Same thing applies for the Tungsten Bee issue.

**Comment by mitchej123** [comment]
Seems it might be a separate issue, reopening for now

**Comment by mitchej123** [comment]
Upon further investigation, Boubou backported it server side (so it works), but if clients aren't updated they'll be displaying the wrong information.  This is indeed fixed in dev based on this.

**Comment by combusterf** [comment]
@MrWye If you are on the officials, when you centrifuge or otherwise process the "wrong" combs, you'll notice the end result is actually correct with respect to the starting bee in question. 

This is the result of the bug being partially fixed server-side. That way setups from before this update would still work, and would also continue to work in the next release. If you set up something now, you'll have to figure what the misnamed comb refers to and set it up with that, and after the update (dunno when) it'll also *look* correct again for you.

Hope that helps!
