### ISSUE TITLE
farming station doesnt like cotton

### ISSUE THREAD

**Issue by jesuseduardo90** [GTNewHorizons/GT-New-Horizons-Modpack#11516]
### Your Pack Version

2.2.0.0

### Your Server

sp

### Your Expectation

I wanna use cotton as intended by the game.
not autocraft crops or pick up from the ground.(Not sure if is intended but apples are drops and still auto pick up and wheat crop doesnt require crafting right?)

### The Reality

I place a cotton crop(natura) and when it auto places it chage it type from 4646:1 to 4646:0 (barley crop), i can place it manual and it kinda work, the cotton is not auto absorbe by the farmer, it just drop on the ground.

Using cotton(Pams) it works but sometimes but sometimes the crop breaks and replants but the crop doesnt refill.

and also why Pams cotton is inferior or something bc requires 2 to convert to 1 natura cotton?

### Your Proposal

a fix idunno.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
I can reproduce cotton dropping on harvest, but cannot reproduce planting wrong seed. The latter should have been fixed by https://github.com/GTNewHorizons/EnderIO/pull/68.
Can you post more detailed setup?

**Comment by jesuseduardo90** [comment]
srry late.
so i use farming station  (ender io)
fertilized dirt (random things)
cotton crops (pams  harvestcraft)
they have a chance of breaking and then planting which leads to using seed from the machine but they dont refill from it harvest. that happen to other (pams) crops. i know you can refilled manual or automatic but idont think thats how the machine should work or maybe yes:v most crops also drops it crop in this case no so i guess thats the problem.

cotton seed (natura)
same thing and worst, sometimes it breaks and use seeds from the machine, if the machine auto plants cotton seed(natura) the result is planting a barley seed (natura).guess some id data stuff error. you know cotton 4646:1 barley 4646:0

**Comment by miozune** [comment]
I can reproduce cotton not going into farmer inventory, but cannot reproduce in dev env. How `PickableFarmer` harvests crops is rather tricky; It uses fake player to actually drop item and then set it dead. So some other mod is breaking it I guess.

**Comment by Porcy** [comment]
2.6.0 and that's still an issue :/ 
Googled the bug and landed here. Tried Natura cotton in the Farming Station and fertilized dirt. The farmer just drops the cotton on the ground. Will add a vacuum hopper as a workaround but a better solution must exist.

**Comment by LazyFleshWasTaken** [comment]
oh, theres a bug? I though our filtering was just weird. Can confirm still an issue for 2.7 beta 2 and 3.
