### ISSUE TITLE
Crash with Neon in Large Titanium Fluid Cell

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#12170]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Put neon in some tank
Click on fluid with empty titanium fluid cell in cursor
Enjoy your crashloop

### Crash Report

[crash-2023-01-02_01.00.50-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10329620/crash-2023-01-02_01.00.50-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by XiaoPangxie732** [comment]
Can confirm. Holding a Large Iridium Fluid Cell filled with Xenon caused the same crash. WITHOUT OptiFine installed

[crash-2023-01-21_22.04.58-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10512367/crash-2023-01-21_22.04.58-client.txt)

**Comment by Glease** [comment]
no longer reproducible in latest dev. probably fixed by one of the fixes to new fluid registrar.
![image](https://user-images.githubusercontent.com/4586901/218254634-3b64b3fe-3618-4b96-b4a8-7aec0a9822cd.png)

**Comment by XiaoPangxie732** [comment]
@Glease Can you confirm that the crash doesn't happen when you hold that cell in your hand? Just putting it in the inventory won't produce the crash in 2.2.8 either

**Comment by Glease** [comment]
![image](https://user-images.githubusercontent.com/4586901/218363452-9f03fd22-0929-4cc4-b0be-b7a309ec5455.png)

**Comment by chochem** [comment]
https://discord.com/channels/181078474394566657/401118216228831252/1097106004866506803

still a problem

**Comment by Miisi** [comment]
still an issue in june 4th nightly
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/46682682/d7f9a8ad-4677-4493-961e-652f6e0b3be7)
opening any machine/hatch's inventory that has neon in it will crash

**Comment by Eason134HK** [comment]
happen on me with Large Tungstensteel Fluid Cell will neon 
ver 2.3.0 (delta)
[crash-2023-07-04_15.06.41-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11945841/crash-2023-07-04_15.06.41-client.txt)

**Comment by combusterf** [comment]
As an added observation, it corrupts the render state for third party viewers of such players.

**Comment by chochem** [comment]
> happen on me with Large Tungstensteel Fluid Cell will neon ver 2.3.0 (delta) [crash-2023-07-04_15.06.41-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11945841/crash-2023-07-04_15.06.41-client.txt)

well as you can see above the fix was April 19th, so after stable came out.
