### ISSUE TITLE
Extreme industrial greenhouse only uses a single crop after restart

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12764]
### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

After restarting the server extreme industrial greenhouses with multiple different crops present in them will only produce the output of a single crop anymore until all crops are removed and re-inserted.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kuba6000** [comment]
What mode are you using? Normal/IC2

**Comment by Tommeh1** [comment]
> What mode are you using? Normal/IC2

IC2

**Comment by Tommeh1** [comment]
Still exists in 2.3.2

**Comment by Tommeh1** [comment]
Did you mean to remove the can't reproduce tag to then immediately re-add it?

**Comment by kuba6000** [comment]
@Tommeh1 

Maybe fixed in
https://github.com/GTNewHorizons/KubaTech/pull/77
https://github.com/GTNewHorizons/KubaTech/releases/tag/0.11.2

If you are playing on the newest version you can try that version

**Comment by dimondmine2** [comment]
@kuba6000 - Jumping in to retest. Just updated server to latest 2.3.4 Beta. Will break controller on all EIGs then refill with crops to ensure clean refresh. Then recheck upon next server restart to report if problem persists in newest version
