### ISSUE TITLE
Connecting P2P across backbone cables do not work consistently

### ISSUE THREAD

**Issue by firenoo** [GTNewHorizons/GT-New-Horizons-Modpack#12905]
### Your GTNH Discord Username

Firenoo#0435

### Your Pack Version

latest AE2 dev

### Your Server

n/a

### Java Version

Java 8

### Type of Server

None

### Your Expectation

From the discussion in https://github.com/GTNewHorizons/EnderIO/pull/105

This simple setup should work. P2P ME Input on the controller, P2P output on the ME drive.

![image](https://user-images.githubusercontent.com/49818773/225040159-a40e5f35-6a49-4e02-8cb0-55c54ce91e8b.png)

### The Reality

The P2P takes an absurd amount of time to resolve, in the meanwhile (visually) flickering on and off. The drive is not accessible in the meantime. 

![image](https://user-images.githubusercontent.com/49818773/225040843-4fce418d-dd63-41cd-945f-94d8ee92bb1c.png)

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
Separating the P2P net to its own subnet fixes it:
![image](https://user-images.githubusercontent.com/49818773/225042164-e6ba95cb-f761-4ae2-986b-569083025816.png)

So the issue happens when:
* P2P network = Main network
* P2P connected across a backbone cable

**Comment by repo-alt** [comment]
It turns out that p2p tunnel triggers reconnection every 20 ticks

**Comment by Auge103** [comment]
I can confirm this issue happening on my server as well.
We have about ~30 channels in use on out "main line", each channel only for a P2P tunnel device, all over one dense cable.
If I replace one block of the dense cable with a backbone cable, the main line will show its channels just fine, but every cable coming out of a connected P2P tunnel will not show used channels at all.

This is what I've been observing:
When a backbone cable is in use, all connected P2P tunnels will show "missing channel" for a really long time.
Every single cable coming out of such a P2P tunnel will show "0 channels". Most of the connected devices will show "missing channel" as well.
But after just a minute, every device is available, you can start crafting patterns, import/export bus will work, everything is working.
But none of these devices as well as cables have visually connected channels. All showing "missing channel" or "0 channels".
Even the network debug tool will show no channels in use, but still all devices work as they should.

Sometimes the channel displaying will start working after ~20-40 minutes, sometimes it will never work. But after each server restart, no channels are shown at all and won't show until you reconnect P2P tunnels.

Even more strange, sometimes when this issue comes up and you cut down a dense cable behind a P2P tunnel and then re-connect it after about a minute, the cable will show the correct amount of channels, but only BEHIND the point where you cut it.
So the cable shows 0 channels and whatever number is in use at the same time in two different connected blocks. This will also persist.
This is shown in the picture below:

![2023-03-13_18 19 00](https://user-images.githubusercontent.com/11227442/225086364-ef0df07a-ac00-473e-bdfc-128dfde94036.png)



I'd like to add in addition to what was described above, that my server maybe had an issue where one of the cables behind a P2P tunnel was probably in an unloaded chunk for a while due to a missing chunkloader.
This caused very similar issues as described above to arise with default **dense cables** instead of backbone ones.
Mainly cables behind P2P tunnels not showing their channels, but connected devices worked fine. 

The server console did show the following output during that time, repeatedly :
```
[14:33:28] [Server thread/WARN] [bdlib]: Received disallowed message component class: scala.collection.immutable.List$SerializationProxy
[14:33:28] [Server thread/WARN] [bdlib]: Received disallowed message component class: scala.collection.immutable.ListSerializeEnd$
[14:33:28] [Server thread/ERROR] [bdlib]: Error decoding packet
net.bdew.lib.network.InvalidClassException: scala.collection.immutable.List$SerializationProxy
        at net.bdew.lib.network.SerializedMessageCodec$$anon$1.resolveClass(SerializedMessageCodec.scala:49) ~[SerializedMessageCodec$$anon$1.class:?]
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1988) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1852) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2186) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_362-362]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_362-362]
        at net.bdew.lib.network.SerializedMessageCodec.decode(SerializedMessageCodec.scala:55) [SerializedMessageCodec.class:?]
        at net.bdew.lib.network.SerializedMessageCodec.decode(SerializedMessageCodec.scala:29) [SerializedMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) [MessageToMessageCodec$2.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) [MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

If you have any further questions or if I can test something for you that can help resolving this issue, then please contact me.

**Comment by albus12138** [comment]
My server is also have this problem. 2.3.0 forge server

I have a long me cable cross unloaded chunks for powering another sub ae network. In my main ae network, not only p2p, me storage bus which directly connected to me controller also lost channel for about one minutes sometimes (seems like when I cross the unloaded chunks, not sure). After I use quartz fiber to split that long me cable before unloaded chunk, this problem was solved.

**Comment by repo-alt** [comment]
I can't reproduce that on the latest version, although pathfinding is untouched. Not sure what has changed

**Comment by firenoo** [comment]
@repo-alt  I did find the underlying cause a while ago, but didn't come up with a fix. Basically, for whatever reason one of the grid nodes on the connected path were reporting used channels = 0, which caused `isActive` to report false. This in turn disconnected the p2ps.

**Comment by repo-alt** [comment]
Can you reliably reproduce that on the current version?

**Comment by firenoo** [comment]
Yeah, still happens in my dev env. The bug happens if p2p tunnels are part of the main net, but not if there's a p2p subnet

**Comment by repo-alt** [comment]
That is unfortunate, because It did reproduce for me too but now when I found time to investigate it works fine...

**Comment by boubou19** [comment]
time to add tons of debug so next one having this bug can send useful data

**Comment by firenoo** [comment]
Can you send how you are trying to reproduce the bug? This is the minimum reproducible setup I have (similar to the one in the original post):
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49818773/d3368714-e428-4dd2-b53f-460b096531c3)

this is in my local experimental branch, but I haven't switched to a new pathfinding algorithm.

**Comment by repo-alt** [comment]
ok, I found the bug, but I'm not sure if the obvious fix won't break something
