### ISSUE TITLE
Milling Balls are not outputed by ME export bus or storage bus

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#13347]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.3.

### Your Server

myFTB

### Java Version

Java 9

### Type of Server

Thermos

### Your Expectation

Export of alumina milling ball via ME into chest

### The Reality

no balls will be put into chest (tested with mini chest, chest chestbuffer), enought available in ME. Export bus (export bus and Storage bus tested) was acive. Tested with and without crafting card.

![grafik](https://user-images.githubusercontent.com/7759876/235288985-c3570d2f-43ff-4b13-a13d-1f1eab73c203.png)
![grafik](https://user-images.githubusercontent.com/7759876/235289073-73fd0df9-4245-484b-a560-ede70436fec6.png)

### Your Proposal

may be a NTB problem

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/235305895-870669da-48c7-40cc-9b55-04e95c607241.png)
Can't reproduce in 2.3.3

**Comment by Tommeh1** [comment]
I can't get ME to handle them either, we're forced to use an assembler attached directly to the ball housings to push straight into the mills.

**Comment by chochem** [comment]
can reproduce. it only works with milling balls from nei which have some nbt. freshly crafted once dont get exported unless you add a fuzzy card, dont know why ngar isnt doing that but still should be fixed.

self crafted:
![image](https://user-images.githubusercontent.com/40274384/235315305-d8423fab-43a6-45a2-96f5-6a8dd9f6fec7.png)

NEI:
![image](https://user-images.githubusercontent.com/40274384/235315324-3a9d8973-a74d-437b-b559-a16bac2009fc.png)

no matter which one I use to set the filter, only the nei variant gets exported. But yea the workaround is also very simple.

**Comment by Tommeh1** [comment]
Unless it has been fixed a fuzzy card still won't allow it to be made and exported by a crafting card.

**Comment by chochem** [comment]
a fuzzy card works. I tested it, you didnt. simple as that.

**Comment by Tommeh1** [comment]
> a fuzzy card works. I tested it.
> 
> well for export bus, crafting card I dont know, maybe try yourself instead of guessing. Crafting cards arent really recommended in general I would say.

Given that all other Isamill bugs still exist i don't expect things to have been fixed, and a crafting card makes a lot of sense here as you only want to keep the ball housing filled.

**Comment by repo-alt** [comment]
crafting card is ok exactly in the scenarios like this, when it is not called very often

**Comment by repo-alt** [comment]
All in all this is more like a GT++ bug, balls should probably be crafted with an NBT tag

**Comment by repo-alt** [comment]
Just tested, fuzzy card + crafting card work fine. Perhaps you should set the pattern output not from NEI so that the assembler output would actually correspond to the pattern output, but anyway, it is not an AE problem.

**Comment by chochem** [comment]
so AE just adding nbt to it for the filtering is normal and intended?

**Comment by repo-alt** [comment]
AE does not add NBT, why? I mean, if the assembler does not produce the expected recipe output, the export bus may not "notice" that the ball is actually crafted, but it will probably "find" the ball the next time it will wake up, unless there is a flag set "export only crafted"

**Comment by chochem** [comment]
no. I tested it with the correct items (no nbt) already in the system. no crafting card  or any of that.

**Comment by repo-alt** [comment]
Eh, not sure I understand

**Comment by chochem** [comment]
freshly crafted no nbt items in the system, use one of them to set the export filter: Does not export.

**Comment by chochem** [comment]
or (again) in more detail:
have both the freshly crafted and the NEI cheated item in the system, use either(!) to set the filter: Will always only export the NEI cheated one. (meaning the filter added nbt to it or something like that when using the freshly crafted to set the filter)

**Comment by repo-alt** [comment]
It is not AE, it is GT unification. Assemnbler produces an item w/o nbt, but as soon as it gets in your inventory after a very short period it will get "unified" to the corresponding oredict item (if the unification is registered that is). This is usually done for all sorts of copper nuggets from all kind of mods but not only for them. Not sure why these balls are unified (to themselves?)

**Comment by chochem** [comment]
keeping them in my inventory for a longer time or throwing them on the ground and picking up again or similar stuff does absolutely nothing here. Also there is no difference between assembler->interface directly, or taking it out myself and then putting in the ae system.

This really seems to be an AE problem.

**Comment by repo-alt** [comment]
do "/mt hand" on a ball taken from the assembler, then wait a bit and do /mt hand again
AE just cannot add nbt to some random items, there may be bugs in comparison, and that I did check for, but not like "import an item and change it", it's not really possible (or at least I'll be very surprized if it is).

**Comment by chochem** [comment]
As I already said: that does nothing.

**Comment by chochem** [comment]
If you continuously dont believe me or dont understand me for whatever reason, then you should really just test it yourself. its really simple.

**Comment by repo-alt** [comment]
I really tested that and I think I undersand all that is going on. I may be mistaken, but I don't see what I else I can do.

**Comment by chochem** [comment]
I guess nobody understands AE code at this point anymore. which is fair., I cant say I do.

**Comment by repo-alt** [comment]
Ok I tested it again and reproduced "something". It may be a bug in setting the filter but more probably it is a bug in a millig ball container item. Notice how when you have in you inventory the balls with and w/o NBT, when they stack - they stach to the item with an NBT. The same happens when you assign a filter. I guess I can add an additional check that the item container does not do weird shit when copying an item, but I think that the item container just should not do that.

**Comment by repo-alt** [comment]
Btw, EnderIO filter does the same as AE filter, which is another argument to _not_ add the check to AE filter creation

**Comment by Ngar1** [comment]
Problem with fuzzy card solved
