### ISSUE TITLE
Pattern termianal opening cause masive spike in ping

### ISSUE THREAD

**Issue by tomasz-brak** [GTNewHorizons/GT-New-Horizons-Modpack#15741]
### Your GTNH Discord Username

baron9972

### Your Pack Version

2.5.1

### Your Server

Private Dedicated, Remote

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

You can create a pattern or use the terminal 

### The Reality

Opening a terminal ping jumps up so high it takes ages to do anything in the terminal.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62989490/bde667e9-81af-409a-a1bf-c8a80838b9c1). This also makes the combo wireless terminal unusable <- The mode of the terminal doesn't matter

### Your Proposal

Make the pattern terminal usable. It should work like crafting terminal. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
The regular pattern terminal? Are you maybe talking about the interface terminal?

As for the regular pattern terminal, the fluid pattern terminal or the fluid processing terminal, I say that I can’t reproduce this. Works fine for me - on 2.5.1 and with a UHV base.

As for the interface terminal, yes it takes a few seconds to load every time you open it. This is being addressed in a different ticket.

**Comment by tomasz-brak** [comment]
https://imgur.com/a/bJ7jYju - ive recorded the actions needed to reproduce
also this issue occurs only when there is more then one person on the server

**Comment by tomasz-brak** [comment]
This issue still occurs on 2.6.0. And i have confirmed with other ppl on my server that it occurs for them.
