### ISSUE TITLE
Flour Can No Longer Be Made In Cooking Table

### ISSUE THREAD

**Issue by Vampurrya** [GTNewHorizons/GT-New-Horizons-Modpack#16330]
### Your GTNH Discord Username

ShrooMoo

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

When having wheat in a fridge, a mortar on a tool rack, and all blocks on connected kitchen floor, I should be able to make flour in the cooking table.

### The Reality

When all conditions above are met, the ability to make flour does not appear. Flour can still be made in a crafting grid or macerator.
![2024-05-20_22 20 30](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/170100787/882baa80-8b33-45f9-b658-2121f303f8ef)
![2024-05-20_22 20 32](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/170100787/fa547087-bc79-4c8a-849c-595d46da3409)

### Your Proposal

Add the ability to make flour back to the cooking table

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@Vampurrya when does it work? in 2.5 1 ?

**Comment by BlueHero233** [comment]
Can reproduce in 2.7
![2024-10-23_17 28 07](https://github.com/user-attachments/assets/c19a7848-9090-4358-b013-1c4bc056df2e)
![2024-10-23_17 28 18](https://github.com/user-attachments/assets/f876263a-906a-4138-8423-42d670825753)

**Comment by Yamnasm** [comment]
Just confirmed that this bug is reproduceable in 2.7.2 (nightly build 815).
Bug occurs using the GregTech Mortar, and also the Pam's HC Mortar and Pestle.

**Comment by dibbydoda** [comment]
I cannot reproduce this bug in Nightly 968, it possibly has been resolved. Tested with both Pam's and GT mortars.

![Image](https://github.com/user-attachments/assets/f9627575-b2d6-4790-95b6-8f2af41e0123)

**Comment by Yoshy2002** [comment]
Seems to be fixed nowadays (Tested with GT and Pams Mortar):
![Image](https://github.com/user-attachments/assets/ecfe7c54-fb85-4616-a102-2838ba3bacb0)
![Image](https://github.com/user-attachments/assets/eb23561f-c651-4d5d-a52d-7b9a8e5cb941)

**Comment by dibbydoda** [comment]
Not reproducible, seems fixed for now

**Comment by Supermouse69** [comment]
Im in 2.7.4 and it seems bug still here

when making it at first time the flour doesnt show but after you do whole game reload it will show eventually
