### ISSUE TITLE
AE2 [fluid]storage bus doesn't work with subnetted interface

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/GT-New-Horizons-Modpack#17872]
### Your GTNH Discord Username

skproch

### Your Pack Version

2.7.0-beta3

### Your Server

private

### Java Version

Java 21

### Type of Server

Ultramine

### Your Expectation

Fluid storage bus connected to dual interface should send fluids to subnet as item storage bus does.

### The Reality

When i place fluid storage bus, set the filtered fluids near the dual interface (subnet), storage bus doesnt' send all this fluids to this subnet.

![image](https://github.com/user-attachments/assets/9550614c-5ca1-4965-a1e5-3c60cc837fcb)

### Your Proposal

Fluid interface should send fluids to subnet.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ruling-0** [comment]
Tested to work on a simple setup on Nightly 727 (filter storage to water, net has fluid terminal, dual interface net has storage, put water in terminal > water stored in dual interface net storage). Can you share more about your setup? Is there storage on the subnet the fluids could be going to instead? Is there storage available on the dual-interface side for the fluid to go to?

**Comment by lordIcocain** [comment]
idk if its related, but i noticed that fluid storage bus with pririty 1 and 0 sometimes swap recived fluid. It is in AL, bus with priority 1 got fluid for bus with 0, bus 0 got fluid for bus 1.

**Comment by SKProCH** [comment]
After a day of sitting with debugger, i figured out 2 main reasons for that:
1. AE2 has user uuids cache file, and for my case there was ids 0 and 1, which are unknown uuids, we don't have this players in server username cache, this ids missing from namemc (and apparently minecraft). Server runs on online mode, and we have license accounts. 
  For some reason my subnet storage busses has owner id 0 (guid from missing player), and security manager rejects attempts to interact with the mainnet.
**This is resolved by editing biometric cards with /nbtedit and putting these cards in security manager.**

There were also cases when I lost access to my AE system when I entered the server. Server in online mode, i've using my license account, so apparently my uuid don't changed.

2. Missing storagebusses handler. 
I've want briefly explain how this works. Every net has a GridCache object, which tracks all the inventories (cells, interfaces, storagebusses, crafting, etc). In my case it holds all subnet storagebusses, cells, etc, but storagebusses which linked to mainnet doesn't have handlers (objects represent an link to inventory kinda). So, apparently seems like when server starts subnet storage busses tries to create a handler, but mainnet interfaces doesn't yet ready, so it creates a null and marks it cached. After that this storage bus doesn't considered as storage variant.  
**After i break and place mainnet interfaces this starts working.** 

------------------
This is explains however, why this issue can't be reproduced: to reproduce it we need a really big mainnet which takes a lot of time to fully initialize, or some bugged player ids in cache.

Probably 2 case can be fixed. I'll try to look at that, but reopening the issue if anyone want's to take a look. Also, i can share my backup if anyone needs it.

**Comment by SKProCH** [comment]
Seems like there is some nbt saving problem. 

Block owner id was saved to "proxyname/p" in nbt data, e.g.:

![image](https://github.com/user-attachments/assets/864210ae-697b-469a-9af2-c034923862aa)

This is a newly placed security manager.


But sometimes this data was lost, this is my mainnet security manager (which was placed by me, my id is 2):

![image](https://github.com/user-attachments/assets/be0cf4ec-9de2-4875-a2c0-4526c8bbb451)

And after that i've lost access to my mainnet (since owner changed from me to user with id 0). This happens a couple times, seems like after server restart. 

If somebody also have this problem (what occasionally security manager refuses to work with owner), please describe your case here.

**Comment by emveevme** [comment]
I might be dumb about something, but it sounds like I have this issue?  I can't figure out how to view the NBT data for the biometric scanner, /nbtedit isn't a recognized command so it must be some external tool I'm unfamiliar with.  I assume that reconfiguring the biometric scanner doesn't fix anything (also this is such a dumb mechanic to be buggy being in single player lol).  

The issue I have definitely seems to affect accessing fluid storage on subnets being accessible from the main-net. 

Hopefully this doesn't just muddy the water on this issue so I'm trying to be as descriptive as possible, I'm nowhere near as knowledgeable when it comes to this stuff.  That being said, the one thing that strikes me as interesting is that setting the priority of the storage bus on the main-net to 1 seemed to remedy the issue like you had noticed as well.  It seemed to fix some other problems I was having, too even though they shouldn't have been related. 

So my EOH setup stores all of its stuff in a dedicated subnet.  The item storage doesn't seem to matter whatsoever.  The fluid storage is the issue, but it's inconsistent - I could see the stellar plasma, but I couldn't see oxygen plasma.  

These are all before the priotity fix:

Here you can see the subnet's storage showing the 109G Oxygen Plasma:
![image](https://github.com/user-attachments/assets/9d895aa8-3aad-49e4-b970-820d1feb17dc)

And the setup with the storage bus connected to the main-net, facing the dual interface on the subnet (this is storage bus started working when I set the priority to 1) 
![image](https://github.com/user-attachments/assets/1add6d16-6b79-47a6-bf12-8fa6c2f3e331)

![image](https://github.com/user-attachments/assets/62a94621-5c29-4128-8968-15b7c972dca0)


You can see the storage bus _does_ recognize the Oxygen plasma in the subnet: 
![image](https://github.com/user-attachments/assets/a5e716c9-6522-4750-b646-746678a8ee33)

If there's anything I can clarify or look in to specifically, just let me know.

**Comment by SKProCH** [comment]
`/nbtedit` command should be added by ServerUtilities (and probably should be available in SP in a last pack versions).

But i don't think this is somehow related to security manager, since you are trying to manipulate the subnet (without security manager) from mainnet. In my case this is being vice versa, and subnet fails the security check trying to manipulate the mainnet. 
But you can check your `world/AE2/settings.cfg` and find the `players` section. For yo (since you play SP) it should contains only one value.

Did this is reproduceable after restart? Or you need to reconfigure storage bus every time? If you return priority back to 0, it stops working?
