### ISSUE TITLE
Time warp/speedup after being AFK on Linux using wlroots-based DEs

### ISSUE THREAD

**Issue by mazunki** [GTNewHorizons/GT-New-Horizons-Modpack#20811]
### Your GTNH Discord Username

mazunki

### Your Pack Version

2.8.b2

### Your Server

private server

### Java Version

Java 21

### Type of Server

None

### Your Expectation

I'm running GTNH on Sway, and leaving the game in another workspace (read: another layout of windows a la virtual desktops, similar to being minimized) causes the in-game time to "freeze" until the window is visible again. This causes time to speed up on return, resulting in what feels like time travel. This is best understood through a video recording: https://youtu.be/cv0YAgzP9D4

I believe the game should show the player in real time after returning from AFK. Some players say they find the behaviour fun, and argue that you can "fix" it by leaving the world and joining again. Personally, I find it very annoying.

### The Reality

I have tested this with qtile (another wlroots based window manager), where it also happens. A few other players on Discord have confirmed it also happens to them using Hyprland (also wlroots). It does not happen on Plasma 6 running on Wayland.

I have also tested this on different versions of `glfw`, both in Wayland mode and in Xwayland mode. I tested with qtile in pure x11 mode, where it does not happen. It seems like the common denominator for the issue is wlroots on multiplayer. The issue does not seem to occur in single player: disabling auto-pause (f3+p) causes time to pass normally when not rendered.

I initially thought this was an opengl issue caused by Wayland forcing all sent frames to be rendered (maybe @eigenraven would be able to confirm or deny this?), but some other people on Discord have suggested that perhaps the network buffer isn't being processed when the window is inactive. I don't know how to test either of these theories.

I would also note that on my end, opening chests and the like doesn't happen until after the time warp finishes; while some other players have said that on their end they haven't had it impact their gameplay at all (i.e. they only see the effect by the sun and in-game time speeding up). I'm not sure what causes that difference.

### Your Proposal

My proposal would be to have a consistent behaviour between all environments. I mostly raise this issue as a request for help to figure out what's causing the behaviour, and help me debug it. My current "solution" of placing the window in a tiny corner of my screen is not practical, nor is having to leave-and-rejoin the server every few minutes when multitasking.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Leeman92** [comment]
To add to this. I do have wayland and plasma 6. Singleplayer. And I experience the same thing. I am not using that f3+p Feature tho.

I experience it with being long away and the screen / Session locking itself.
I do have the same thing tho as in I cannot break or place Blocks during the - as you called it - time travel.

**Comment by mazunki** [comment]
@Leeman92 In single player, the game will automatically pause if you lose focus. That's an intentional feature of Minecraft. Try disabling auto-pause with `f3+p` to see if it still happens to you (you'll have to disable the keybind on `p` for it to not conflict). I'm surprised you experience time travel at all, given that it should pause? Interesting.

**Comment by mazunki** [comment]
I ran sparkc with different timeout intervals when the window was inactive, which seem to suggest that the game is trying to render itself even when the window isn't actually visible, given the references to `org.lwjglx.opengl.Display.update()` and `org.lwjgl.glfw.GLFW.glfwSwapBuffers()`.
- https://spark.lucko.me/ev7s4B8l6i
- https://spark.lucko.me/4DT1z4cT4G
- https://spark.lucko.me/X7KwTX0XFK

and I also profiled /during/ the time warp (i.e. after returning to the game):
- https://spark.lucko.me/YBJtVYFALK
- https://spark.lucko.me/sj95cHYoln

Someone on Discord also thought it's worth mentioning that physics does /not/ affect the player when the window is out-of-view: water flowing does not move the player at all.

**Comment by toadjaune** [comment]
Extra data point here : 
- pack version 2.7.4 (but the issue has been present as far as I can remember)
- sway (so, wlroots-based), on fedora

I can confirm the time warp, and took the habitude to afk in my spectre dim, as this seems to speed up the backlog (not precisely measured, just a feel)

In singleplayer the game indeed pauses, so, not observable there.

Let me know if you want me to test anything on my end !

**Comment by mazunki** [comment]
I just realized this doesn't happen in the personal dimension! Is this the same for other people? What's different between the personal dimension and the overworld?

**Comment by toadjaune** [comment]
I'm pretty sure it does happen in personal dimension, although the backlog is way faster.
I can confirm this next week (I'm not currently close to my desktop computer) if necessary !

**Comment by mazunki** [comment]
@toadjaune that'd be nice. Do you have daylight cycle turned on in your personal dimension? If so, does the time warp disappear if you turn it off? I just experimented what you said by turning the daylight cycle on.

Edit: I just had it happen even with daylight cycle frozen. No other settings changed, as far as I know. Hm.

**Comment by toadjaune** [comment]
I can confirm that the issue is present even with daylight cycle disabled !

**Comment by LunarLambda** [comment]
Oh that's really funny I thought the AFK timewarp was some kind of modpack feature (by e.g. having the server not send world updates to afk players, or having the client buffer them until the window is back to save resources)

This just being wayland jank is hilarious

**Comment by toadjaune** [comment]
> Oh that's really funny I thought the AFK timewarp was some kind of modpack feature (by e.g. having the server not send world updates to afk players, or having the client buffer them until the window is back to save resources)

I suspect it's the latter (client buffering the changes without rendering them in the void), as being afk for too long (we're talking ~days) eventually crashes the client in my experience (although this could be unrelated, as, you know, such a modpack aggregates lots of code of various quality from heterogenous sources)

> This just being wayland jank is hilarious

Funnily enough, I suspect this could be a "works as intended somewhere in the graphical stack that's supposed to pause on focus loss, but never worked with X because it didn't advertise properly the loss of focus" type of situation ^^

**Comment by RecursivePineapple** [comment]
I can confirm that this happens for me in SP. I haven't noticed it in MP but I also haven't specifically tested it. I never have my dev instances on the same workspace as my IDE so I don't know if alt + tabbing also does this, but putting the game on a hidden workspace tends to cause this problem.

**Comment by mazunki** [comment]
> Funnily enough, I suspect this could be a "works as intended somewhere in the graphical stack that's supposed to pause on focus loss, but never worked with X because it didn't advertise properly the loss of focus" type of situation ^^

My understanding is exactly this, from interpreting the sparkc logs, and this snippet of code:
<img width="554" height="206" alt="Image" src="https://github.com/user-attachments/assets/5ad8e2d2-80fb-4e1c-9252-d5e9cd5cc655" />

**Comment by toadjaune** [comment]
> > Funnily enough, I suspect this could be a "works as intended somewhere in the graphical stack that's supposed to pause on focus loss, but never worked with X because it didn't advertise properly the loss of focus" type of situation ^^
> 
> My understanding is exactly this, from interpreting the sparkc logs, and this snippet of code

Interesting, although that alone doesn't explain why world updates end up being queued instead of processed but not rendered.

Maybe somehow `swapBuffers` is required for ticking forward ? That would be surprising, but you never know...

Is the code containing this screenshot available online somewhere ? Now I'm curious ^^

**Comment by mazunki** [comment]
Not sure where hael got it from:

https://discord.com/channels/181078474394566657/181078474394566657/1404509223143870474

**Comment by eigenraven** [comment]
Fixed in lwjgl3ify 3.x

**Comment by mazunki** [comment]
omg thanks for fixing it. Is it possible to test this right away, or would that require using a daily?

**Comment by mazunki** [comment]
Can confirm it works :)

Updating to 3.x also fixed my SEUS shaders segfaulting.

**Comment by AnujCtrl** [comment]
> Can confirm it works :)
> 
> Updating to 3.x also fixed my SEUS shaders segfaulting.

How did you update, update to 3.0.14 on GTNH stable 2.8.4 (Java 15-21) is giving me a crash. 
Still facing this issue,

**Comment by PLASMAchicken** [comment]
@AnujCtrl You need to update the lwjgl3ify mod + multimc/prism patch

lwjgl3ify-3.x.x.jar
for mods folder
disable/delete old one 

lwjgl3ify-3.x.x-multimc.zip
open the instance folder and copy the contents of the zip into it
replacing the old mmc-pack.json + overwrite any files in the folders
