### ISSUE TITLE
Client crash when sorting an inventory with Tinker Steel Hammer inside

### ISSUE THREAD

**Issue by Dovahkill** [GTNewHorizons/GT-New-Horizons-Modpack#21842]
### Your GTNH Discord Username

Neutron

### Your Pack Version

2.8.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Actions

Sort any inventory with my Steel Hammer inside.

**Hammer trigger exception :** 
<img width="489" height="405" alt="Image" src="https://github.com/user-attachments/assets/edfb3706-5d12-4102-af38-3f5dd2616aef" />

All my others Tinker's tool works.

### Crash Report

<img width="2286" height="193" alt="Image" src="https://github.com/user-attachments/assets/f74fe954-e8d2-4242-8f31-9a97d5fe02a0" />

**Stack trace from fml-client:**
`[21:24:56] [Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.itemSortRules" is null
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.lambda$new$0(SortHandler.java:115) ~[SortHandler.class:?]
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
	at java.base/java.util.TimSort.sort(TimSort.java:234) ~[?:?]
	at java.base/java.util.Arrays.sort(Arrays.java:1234) ~[?:?]
	at java.base/java.util.List.sort(List.java:509) ~[?:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sortHorizontal(SortHandler.java:157) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sort(SortHandler.java:144) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sort(SortHandler.java:135) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sort(SortHandler.java:130) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.network.CSort.executeServer(CSort.java:92) ~[CSort.class:?]
	at Launch//com.cleanroommc.bogosorter.common.network.NetworkHandler.lambda$static$1(NetworkHandler.java:61) ~[NetworkHandler.class:?]
	at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [netty-all-4.0.10.Final.jar:?]
	at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[21:24:56] [Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.itemSortRules" is null
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.lambda$new$0(SortHandler.java:115) ~[SortHandler.class:?]
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
	at java.base/java.util.TimSort.sort(TimSort.java:234) ~[?:?]
	at java.base/java.util.Arrays.sort(Arrays.java:1234) ~[?:?]
	at java.base/java.util.List.sort(List.java:509) ~[?:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sortHorizontal(SortHandler.java:157) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sort(SortHandler.java:144) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sort(SortHandler.java:135) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sort(SortHandler.java:130) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.network.CSort.executeServer(CSort.java:92) ~[CSort.class:?]
	at Launch//com.cleanroommc.bogosorter.common.network.NetworkHandler.lambda$static$1(NetworkHandler.java:61) ~[NetworkHandler.class:?]
	at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [netty-all-4.0.10.Final.jar:?]
	at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[21:24:56] [Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.itemSortRules" is null
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.lambda$new$0(SortHandler.java:115) ~[SortHandler.class:?]
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
	at java.base/java.util.TimSort.sort(TimSort.java:234) ~[?:?]
	at java.base/java.util.Arrays.sort(Arrays.java:1234) ~[?:?]
	at java.base/java.util.List.sort(List.java:509) ~[?:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sortHorizontal(SortHandler.java:157) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sort(SortHandler.java:144) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sort(SortHandler.java:135) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sort(SortHandler.java:130) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.network.CSort.executeServer(CSort.java:92) ~[CSort.class:?]
	at Launch//com.cleanroommc.bogosorter.common.network.NetworkHandler.lambda$static$1(NetworkHandler.java:61) ~[NetworkHandler.class:?]
	at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [netty-all-4.0.10.Final.jar:?]
	at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[21:24:56] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel bogosorter
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.itemSortRules" is null
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.lambda$new$0(SortHandler.java:115) ~[SortHandler.class:?]
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
	at java.base/java.util.TimSort.sort(TimSort.java:234) ~[?:?]
	at java.base/java.util.Arrays.sort(Arrays.java:1234) ~[?:?]
	at java.base/java.util.List.sort(List.java:509) ~[?:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sortHorizontal(SortHandler.java:157) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sort(SortHandler.java:144) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sort(SortHandler.java:135) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.sort.SortHandler.sort(SortHandler.java:130) ~[SortHandler.class:?]
	at Launch//com.cleanroommc.bogosorter.common.network.CSort.executeServer(CSort.java:92) ~[CSort.class:?]
	at Launch//com.cleanroommc.bogosorter.common.network.NetworkHandler.lambda$static$1(NetworkHandler.java:61) ~[NetworkHandler.class:?]
	at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[21:24:56] [Netty Client IO #0/INFO] [THAUMCRAFT/]: Restoring client configs.
[21:24:56] [Netty Client IO #0/DEBUG] [EnderCore/]: Skipping syncing field com.enderio.core.common.config.ConfigHandler.showRegistryNameTooltips as it was marked NoSync
[21:24:56] [Netty Client IO #0/DEBUG] [EnderCore/]: Skipping syncing field com.enderio.core.common.config.ConfigHandler.disableVoidFog as it was marked NoSync
[21:24:56] [Netty Client IO #0/DEBUG] [EnderCore/]: Skipping syncing field com.enderio.core.common.config.ConfigHandler.textureErrorRemover as it was marked NoSync
[21:24:56] [Netty Client IO #0/DEBUG] [EnderCore/]: Skipping syncing field com.enderio.core.common.config.ConfigHandler.showDurabilityTooltips as it was marked NoSync
[21:24:56] [Netty Client IO #0/DEBUG] [EnderCore/]: Skipping syncing field com.enderio.core.common.config.ConfigHandler.defaultModSort as it was marked NoSync
[21:24:56] [Netty Client IO #0/DEBUG] [EnderCore/]: Skipping syncing field com.enderio.core.common.config.ConfigHandler.showOredictTooltips as it was marked NoSync
[21:24:56] [Netty Client IO #0/INFO] [EnderCore/]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[21:24:56] [Netty Client IO #0/INFO] [EnderCore/]: Reset configs to client values for tterrag.wailaplugins.config.WPConfigHandler
[21:24:56] [Netty Client IO #0/INFO] [FML/]: Deregistering PersonalSpace dimension 181
`

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by DarkShadow44** [comment]
Does this also happen with a fresh steel hammer? I tried with one from NEI but there was no crash. Although I use InventoryBogoSoter 1.3.11-GTNH.

**Comment by grechagrecha** [comment]
This exact issue was also happening to me, seems that updating to 2.8.1 fixed it.

**Comment by NeutronSelector** [comment]
@DarkShadow44 With a fresh steel hammer, no issue. 
I tried to copy exact same hammer with NEI (tape R on it for put it in the history section), load my creative world and retake the hammer from history of NEI, same befavior. 
I tried to rename my hammer in enderIO anvil, first time, impossible to set any name. I pickup the hammer in right GUI case, 12 lvl of XP cosumed and the hammer is renemed in "fffffffffffffff". After that, when i put the hammer in second time in anvil, this time can i set a name normaly. Then, now my hammer can be sorted correctly without any crash.

I dont now what... but i'ts ok for me. The issue is fixed. (I still in 2.8.0).

**Comment by NeutronSelector** [comment]
I also try with InventoryBogoSoter 1.3.11-GTNH, the crash occur exactly same thing

**Comment by Mitaka12103** [comment]
Issue still exists on 2.8.4 when the Display Name sort rule is used. Also happens with a lumber axe and shuriken.

**Comment by DarkShadow44** [comment]
> Issue still exists on 2.8.4 when the Display Name sort rule is used. Also happens with a lumber axe and shuriken.

Can you provide a save that has that issue?

**Comment by Mitaka12103** [comment]
https://gofile.io/d/yc80ql

**Comment by DarkShadow44** [comment]
How did you manage to get an item with such a long name?

Your name is 

```§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§f§fHaha, reference```

which is longer than expected, causing that issue.

If you give me instructions on how exactly to reproduce that in a new world I can fix that.

**Comment by Mitaka12103** [comment]
All of my other TiC tools that don't crash have either a  `§f` or `§r` at the start of their names. Not sure how but I assume it happened after an update. Renaming them in an anvil fixed it.

**Comment by DarkShadow44** [comment]
This specific crash with name too long will be fixed in the next version, please let me know if there is further issues.
