### ISSUE TITLE
Jabba Barrels items and bibliocraft fancy sign text causing render shenanigans with Angelica + Shaders

### ISSUE THREAD

**Issue by ObviousLemon** [GTNewHorizons/GT-New-Horizons-Modpack#21932]
### Your GTNH Discord Username

ObviousLemon

### Your Pack Version

2.8.0 Daily 183

### Your Server

Iota

### Java Version

Java 25

### Type of Server

None

### Your Expectation

Not having chests change from expected brightness to significantly bright randomly based on where you are facing when a Jabba barrel is rendered
No Jabba barrel, with BSL shaders.
<img width="1423" height="745" alt="Image" src="https://github.com/user-attachments/assets/e1306dc6-8076-47ec-a1cc-b3b37d85662d" />
With Jabba barrel, with BSL shaders, without stored items.
<img width="1385" height="899" alt="Image" src="https://github.com/user-attachments/assets/930320cb-fcb9-4e0d-8b15-86559fc64aed" />
With Jabba barrel, with BSL shaders, with stored items.
<img width="1233" height="761" alt="Image" src="https://github.com/user-attachments/assets/db702fbc-0e22-48b9-ba94-81a1aa9c4a2c" />
With Jabba barrel, with Complementary shaders, with stored items.
<img width="1333" height="797" alt="Image" src="https://github.com/user-attachments/assets/69ff6420-4871-4e30-a620-ace6da357e86" />
Bibliocraft sign no text with shaders
<img width="1725" height="783" alt="Image" src="https://github.com/user-attachments/assets/4377de98-018a-4fac-a7d1-23d2f25799d1" />
With text With shaders
<img width="1807" height="815" alt="Image" src="https://github.com/user-attachments/assets/38882b41-3512-4048-8b3c-e281785ff966" />
With Storage drawers, with BSL shaders, with stored items.
<img width="1321" height="799" alt="Image" src="https://github.com/user-attachments/assets/31dfc45d-4335-4f72-a187-5a044970b6a8" />

### The Reality

Regular play involves chests and other assorted tile entities flickering between unaffected and brightened states as you move around.

### Your Proposal

Fix - https://github.com/GTNewHorizons/Jabba/pull/33 covers this exact issue with the exact same symptoms, since it has returned it may be worth checking if the previous fix is merged into this version of the pack.

### Final Checklist

- [ ] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by sisyphussy** [comment]
Probably an issue with https://github.com/GTNewHorizons/Angelica/pull/1017

**Comment by timb8g** [comment]
For information setting config option "enableFontRenderer" to false solves this issue.

**Comment by DeathFuel** [comment]
Most likely fixed in https://github.com/GTNewHorizons/Angelica/pull/1040 (commit  [b6bfb9c](https://github.com/GTNewHorizons/Angelica/pull/1040/commits/b6bfb9c596bdf523851f02acc751c3f12760178a)). Try disabling font AA and see if the issue no longer appears.

**Comment by ObviousLemon** [comment]
Setting "enableFontRenderer" to false fixed this issue for me, thanks.

**Comment by Zyin055** [comment]
Changing `B:enableFontRenderer=true` to `B:enableFontRenderer=false` in `.minecraft\config\angelica-options.json` helped reduce how often the bug happens for me in GTNH 2.8.1 (angelica-1.0.0-beta62). It started happening randomly with Complimentary Shaders enabled when looking a specific direction. Not using any JABBA barrels or signs. Removing any trophies I placed in the world seems to help.

I tried manually updated Angelica to beta68, which supposedly fixes the issue, but the game freezes when loading.

Edit: updating to 2.8.3 did not fix it, which uses angelica-1.0.0-beta66b.

**Comment by DeathFuel** [comment]
> I tried manually updated Angelica to beta68, which supposedly fixes the issue, but the game freezes when loading.

Try updating the dependencies, too. If that doesn't work, please open an issue with logs attached

**Comment by austin1346** [comment]
Currently running GTNH 2.8.4, Angelica 1.0.0 Beta 78, and GTNHLIB 0.8.21 and this issue still exists, exactly the same as the above screenshots. I have tried setting enableFontRenderer to false in mod config options, reloaded and no change.
