### ISSUE TITLE
obzinite still has oredict alumite

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#22282]
### Your GTNH Discord Username

chochem

### Your Pack Version

2.8.1

### Your Server

SP

### Java Version

Java 25

### Type of Server

Single Player

### Your Expectation

I expect obzinite to be obzinite.

### The Reality

oredict:
<img width="461" height="212" alt="Image" src="https://github.com/user-attachments/assets/aecebdc0-c233-429c-bfca-4d41b4fac741" />
quest:
<img width="575" height="130" alt="Image" src="https://github.com/user-attachments/assets/49352b1a-da5d-4b24-9589-84df6755f2eb" />

### Your Proposal

rename the material fully and not just half way.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by loenaaaa** [comment]
Fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/5628

**Comment by YannickMG** [comment]
@chochem I should point out that this isn't a "fix" but a change. The material name was purposefully kept as "Alumite" for a number of reasons.
- Most importantly, it made the transition easier for players who were used to the Alumite name, since Obzinite still showed up when searching Alumite.
- It avoids the need for the an OreDict migration
- It kept maximum compatibility with unsupported (by us) GT addons

Since it's been a while since the transition, the original reason (still allow searching for alumite) isn't as strong, but it was still seen as a desirable feature at the time Obzinite was introduced. "Fixing" this would remove this "feature".

Would you still like to go ahead with this change given this additional context?

**Comment by chochem** [comment]
I mean you do see the picture above, so yea it is clearly bugged right now. That this was intentional does not really make it better.
I am aware that this might need effort to do properly and that it might not be considered high priority. GT materials should go by id, so no transition needed there, tinkers is the bigger concern probably.

Unsupported 'GT addons' are obviously not relevant, our GT fork is GTNH-only. See https://docs.google.com/spreadsheets/d/1LHd8c4FLLHiJqsuTppF2XFTE6bh-mXE7afVwGbzOKms/

**Comment by loenaaaa** [comment]
Most migrations usually give a one-update buffer, don't they? So 2.7 still uses alumite fully, 2.8 now uses obzinite but with support for alumite, and then 2.9 fully "deprecates" alumite. I think it's fine because obzinite is relatively early in game progression so you won't get too many people who are used to alumite now left in the dark.

**Comment by NotKaizul** [comment]
Sometimes obzinite tinkers tools get named alumite as well

<img width="347" height="227" alt="Image" src="https://github.com/user-attachments/assets/a804aca9-476a-4a3b-bff1-6ce0ca7d1273" />
