### ISSUE TITLE
Holding down Q is broken in experimental 52

### ISSUE THREAD

**Issue by firedemontwinkie** [GTNewHorizons/GT-New-Horizons-Modpack#22878]
### Your GTNH Discord Username

firedemontwinkie

### Your Pack Version

experimental 52

### Your Server

Zeta

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

in previous verson you could hold down Q to drop indivual items from the stack in hand fast. The reason why you want to do this is when you are using a thaumcraft crucible you lose a lot of items if you drop the stack insted of indivualy.

### The Reality

one item is droped on the ground as if you only pressed Q once. this happens to other people. on servers and on single player

### Your Proposal

revirt it to orignal behaveor. 

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by PLASMAchicken** [comment]
> when you are using a thaumcraft crucible you lose a lot of items if you drop the stack insted of indivualy.

Should be fixed in Salis Arcana [1.1.36-GTNH](https://github.com/GTNewHorizons/Salis-Arcana/releases/tag/1.1.36-GTNH) via https://github.com/rndmorris/Salis-Arcana/pull/402

**Comment by firedemontwinkie** [comment]
well, I still cant flex on the homies

**Comment by PLASMAchicken** [comment]
When was it last fine experimental 51 or 50?

**Comment by PLASMAchicken** [comment]
Try downgrading hodgepodge to the last working version you used, that changed some stuff related to Q, possibly thats it


Maybe cause by the change from Inventory Tweaks to BogoSorter

**Comment by Xiarno** [comment]
Still an issue on daily 502 by the way.

Edit: Fixed it by doing this: https://github.com/GTNewHorizons/lwjgl3ify/issues/310#issuecomment-4479327986
