### ISSUE TITLE
wrong number of potassium dichromate dust in quest #1702

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#4032]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Was following the quest "Potassium Dichromate" (number 1702).
#
#### What happend instead? (Attach screenshots if needed)
the quest requires 8 ammonia cells and 8 potassium dusts, then 8 potassium dichromate dusts.
But the recipes is a 2:1 ratio:
![image](https://user-images.githubusercontent.com/12850933/51803253-48c4d580-2253-11e9-8f44-1126f449d044.png)
it makes you recraft 8 potassium dust and 8 ammonia cells to complete the quest.
#
#### What do you suggest instead/what changes do you propose?
Either change the ammonia cells& potassium dust amounts required or the potassium dichromate dust amount required.

**Comment by Dream-Master** [comment]
will do

**Comment by Dream-Master** [comment]
fixed in 2.0.6.6a.dev
![image](https://user-images.githubusercontent.com/2970688/51936364-4bb4f700-2408-11e9-980b-d6978cfba66c.png)
![image](https://user-images.githubusercontent.com/2970688/51936374-4f487e00-2408-11e9-9697-3bd64c5c830d.png)

**Comment by DietmarKracht** [comment]
Still not fixed in 2.0.7.0

**Comment by Dream-Master** [comment]
will check

**Comment by Prometheus0000** [comment]
This is still not fixed, the potassium dichromate required should be 4, not 8. Though I'm not sure why you need to make more than two, since the next quest only needs 10 tiny dusts. Running 2.0.8.5dev.

**Comment by chochem** [comment]
@Prometheus0000 its also on my list: https://github.com/GTNewHorizons/NewHorizons/issues/5457
though it seem no dev has really looked at that list yet.
