### ISSUE TITLE
Quest book reapetable quest need repair

### ISSUE THREAD

**Issue by DarkGaterau** [GTNewHorizons/GT-New-Horizons-Modpack#5540]
Reward Area quest not repetable https://i.imgur.com/qNxDHSE.png
Kill all the things quest not repetable and have -coldown https://i.imgur.com/4Rz6uQg.png  https://i.imgur.com/wQrPLOb.png

**Comment by Dream-Master** [comment]
@funwayguy is this a known error or a new one. Or is this fixed in newer version 322 of BQ3?

**Comment by Funwayguy** [comment]
What version is that? I thought I fixed that exact bug a while ago

**Comment by DarkGaterau** [comment]
> What version is that? I thought I fixed that exact bug a while ago

@Funwayguy BetterQuesting-3.0.320.jar

gtnh version 2.0.8.3

**Comment by Dream-Master** [comment]
[mods.zip](https://github.com/GTNewHorizons/NewHorizons/files/4177211/mods.zip)
@DarkGaterau please test with this new updated mods

**Comment by Funwayguy** [comment]
Would this be happening on a server by chance?

I've checked the code and the repeat sort order issue that previously caused this has been fixed but you can still have the tooltip display negative time if the your or the server clock is out of sync. Otherwise the repeat should still occur on time (relative to the server that is)

**Comment by adopio** [comment]
Yes it is happening on serwer.
I'm not sure if on all server with lattest update but for sure on ETA serwer.

**Comment by DarkGaterau** [comment]
@Funwayguy OK. Does the code take into account the time zone?
also we tested in single BetterQuesting-3.0.322 StandardExpansion-3.0.174.jar

repeatTime set to 0 quest dont open again rise to 20 and 200 and no effect timer go from 10 to 0 and go down in -. quest dont start again

**Comment by Funwayguy** [comment]
Timezone is irrelevant. It works off the unix timestamp. There may be cases where the UI simply hasn't refreshed due to the old netcode.

**Comment by boubou19** [comment]
if the edit mode is activated on a server, everyone has his cooldown for repeatable quests frozen

**Comment by Prometheus0000** [comment]
According to leagris this also happens in SP.
