### ISSUE TITLE
UnknownNutrientAgar not show up recipe use in NEI

### ISSUE THREAD

**Issue by SBAngel810** [GTNewHorizons/GT-New-Horizons-Modpack#6240]
#### Which modpack version are you using?
2.0.9.0QF2
#
#### What did you try to do, and what did you expect to happen?
![20200611194937](https://user-images.githubusercontent.com/66779899/84382209-edfc0600-ac1c-11ea-8097-495df9af0bb1.png)
The unknown water on T Ceti E can use to make UnknownNutrientAgar, but UnknownNutrientAgar can't make anything
#
#### What do you suggest instead/what changes do you propose?
If it actually can use on something but can't show on NEI, explain it in quest book, otherwise add some use to it or delete it

**Comment by chochem** [comment]
its not useless. just a (known) bug about bacterial vat recipes not showing when looking by uses (works fine if looking by recipes).

![image](https://user-images.githubusercontent.com/40274384/84383038-778ee200-abe3-11ea-806a-abf4c2e4b967.png)

**Comment by chochem** [comment]
the quests are also in the works (they might even be in QF3, I havent checked yet)

**Comment by SBAngel810** [comment]
thanks for explain it. So will this bug be fixed in future version?

**Comment by chochem** [comment]
@bartimaeusnek

**Comment by Dream-Master** [comment]
its still an issue with Nei and Bartworks

**Comment by Prometheus0000** [comment]
I mentioned using it in the making seaweed quest in UHV I believe.

**Comment by GTNH-Colen** [comment]
BW fluids seem to have a few weird issues, like the fact it still can't be used in SFM without breaking. Really odd behaviour at play and I've no clue why.

**Comment by Prometheus0000** [comment]
Petri dishes will not show up in their bio lab recipes either for example. And Agar is used in Raw Growth Medium, but it just shows the LCR recipe above. Same for all the biolab and vat recipes and their components that aren't cultures basically.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/bartworks/pull/102
