### ISSUE TITLE
HTTPS-version of gtnewhorizons.com not a thing

### ISSUE THREAD

**Issue by OParczyk** [GTNewHorizons/GT-New-Horizons-Modpack#7198]
#### Which modpack version are you using?
n/A
#
#### If in multiplayer; On which server does this happen? 
n/A
#
#### What did you try to do, and what did you expect to happen?
I use HTTPS Everywhere. Clicked on the http://gtnewhorizons.com/ link on the front page of the repo, so due to the plugin I went to https://gtnewhorizons.com/.

I expected that either a) this page is the same as https://www.gtnewhorizons.com/ or b) to be redirected there
#
#### What happened instead? (Attach screenshots if needed)
The certificate of "gtnewhorizons.com" is only valid for "*.enjin.com, enjin.com"
After granting an exception, https://gtnewhorizons.com/ yielded a 403 Page from cloudflare.
#
#### What do you suggest instead/what changes do you propose?
I don't know how your hosting works, but I propose extending your certificate to include the non-www.-version and make the redirect work or to move the presence from "www.gtnewhorizons.com" to just "gtnewhorizons.com".
AFAIK some browsers are starting to warn users about non-https-websites and start to implement features like HTTPS Everywhere into their standard versions.
Although I guess that that redirect isn't something too bad privacy wise I still think this should be addressed.

**Comment by bombcar** [comment]
This is fixed and can be closed. https://www.gtnewhorizons.com works fine.

**Comment by glowredman** [comment]
Would be nice to have HTTPS on http://downloads.gtnewhorizons.com and http://jenkins.usrv.eu aswell

**Comment by Dream-Master** [comment]
will ask namikon about it

**Comment by bombcar** [comment]
Jenkins maybe trickier because it’s on a custom port

**Comment by OParczyk** [comment]
[https://www.gtnewhorizons.com](https://www.gtnewhorizons.com) always worked fine. What was my original issue and still doesn't work for me is [https://gtnewhorizons.com](https://gtnewhorizons.com), which is linked to from the repo page.

It no longer yields a 403 but a timeout.

**Comment by OParczyk** [comment]
@mitchej123 Unless it takes a couple of days for your recent fix to trickle through your hosting scheme, the issue still persists.

There is still no [https://gtnewhorizons.com/](https://gtnewhorizons.com/), only on the `www` subdomain, there is HTTPS support.
As wished above too, there still is neither [https://downloads.gtnewhorizons.com/](https://downloads.gtnewhorizons.com/) nor [https://jenkins.usrv.eu/](https://jenkins.usrv.eu/).

Does your hosting scheme take a couple of days to make your changes visible, or why have you marked this issue as completed when the issue still persists?

**Comment by mitchej123** [comment]
GitHub added the "as completed". I just closed it because it was old and no comments since November

**Comment by OParczyk** [comment]
Thank you for the fast response!
I don't think closing the issue when the issue still persists is a good thing. I can see how this one might be of low priority to many here, but resolved it isn't.
Do you suggest opening a new one about the same issue every couple of months of them (seemingly) not being worked on?

**Comment by mitchej123** [comment]
We've got over 1000 open issues.  With so many open issues legitimate issues get lost in the noise.  To combat this I'm closing any old one that has 1) no movement 2) no interest 3) no sign anyone is going to work on it.   Any relevant issue that is incorrectly closed, that someone will work on, will be reopened.

The hosting is directly under the control of Nami, with help from Dream and Boubou.  They're the only ones who can do anything about this particular issue.  Please hit up Dream in discord and see if this issue can/will be addressed by them, and we can re-open.  


Please do not create duplicate tickets.
