### ISSUE TITLE
4A machine don`t work fine

### ISSUE THREAD

**Issue by Sakura-sama** [GTNewHorizons/GT-New-Horizons-Modpack#7516]
#### Which modpack version are you using?

  2090
#### If in multiplayer; On which server does this happen? 

   multiplayer
#### What did you try to do, and what did you expect to happen?

  I want to use two luv energy hatch to get my assemble line working in zpm,while I give my assemble line 4A luv to work,it often stopped cause of less of energy.
#### What happened instead? (Attach screenshots if needed)

  Given 4A luv but stop
#### What do you suggest instead/what changes do you propose?
   1.Make the capacity of energy hatch bigger. With the Voltage tier higher,the capaity of energy hatch are a bit low to keep these multi-machine with two energy hatches running fine.
    2.Give the main controler a capacity,like the fusion controler.

**Comment by yukieiji** [comment]
This is probably caused by a momentary EU shortage due to insufficient output from the generator or main battery, so installing a battery buffer(include two battery) next to the energy hatch should solve the problem.

**Comment by Sakura-sama** [comment]
Well,my output hatch give 16A luv,and I use 1x dargon wire to transfer energy,with cost about 100eu/t.On all the hands,my assemble line should work fine,but it stop several times.
So I place a 4A luv Diode to make my assemble line work fine,with capacity about five times of energy hatch's.My assm=emble line still not work fine,with the Diode allways not empty.
I find that a mulit-block machine with two energy hatchs allways require more energy from one energy hatch and less the other one,this point makes my assemble line stopped several times,now I'm using two 2A luv Diode placing by the energy hatch to solve this problem,I think increase the capacity of energy hatch will be better.

**Comment by GTNH-Afx237v7** [comment]
Use a wire that is suitable for LuV - either superconductor, or HSS-G.

**Comment by Prometheus0000** [comment]
My understanding is that energy hatches all have the same amount of power as a multiple of the tier voltage. There's no reason for you to run out of power as long as you supply it properly. If there was a problem with the amount, it would affect all tiers and multis. Since that is not the case, it is almost assuredly user error.

**Comment by yukieiji** [comment]
The following setups didn't stop Assembling Line.
This means that there is something wrong with your base.

![2021-02-23_16 26 04](https://user-images.githubusercontent.com/40425798/108813487-73c9b100-75f4-11eb-83a1-4440f189973a.png)
![2021-02-23_16 26 08](https://user-images.githubusercontent.com/40425798/108813495-77f5ce80-75f4-11eb-8f7f-f569ce82cc3d.png)

**Comment by Sakura-sama** [comment]
Well,I don't know how to put a picture up here,so it's hard to show my setup.
First,1x dargon wire is suitable for a luv machine,I need a higher Amp wire so I use it but HSS-G
Second,I know the mulit between capacity and vol are same,but only my luv assemble line don't work fine.
Third,my assemble line can get energy with 4A 32680EU/T ,is more than a ZPM energy hatch needs:122880EU/T,so it's hard to imagine my assemble line can't work well.
I guess machine will get 65536EU/T from one hatch but 57344EU/T the other,so I can't maintain the machine work

**Comment by Prometheus0000** [comment]
Either use the MC screenshot key F12, or if using win10, use Win+Shift+S and select an area to copy. Also, I don't think there's a 'dargon' material?

**Comment by GTNH-Afx237v7** [comment]
Screenshot key is F2. You can drag&drop pictures directly into the text field.
I assume you are using Draconium wires?

**Comment by Sakura-sama** [comment]
![QQ截图20210223162615](https://user-images.githubusercontent.com/58065326/108818153-f1d98800-75f3-11eb-9615-5d1350af8eb6.png)
yes,I'm using Chinese versions,so I don't know the true name of these material

**Comment by GTNH-Afx237v7** [comment]
Have you tried using an actual LuV cable? LuV superconductors already offer 8A for a 1x wire, so a 2x will transport all of the 16A out of your dynamo hatch. I suggest you try this, if the issue still exists then we would need more pictures of the setup.

**Comment by Sakura-sama** [comment]
![QQ截图20210223163502](https://user-images.githubusercontent.com/58065326/108818946-1b46e380-75f5-11eb-925d-d017d42b4a36.png)
Actually,this setup I'm using now also can solve this problem

**Comment by GTNH-Afx237v7** [comment]
Not a bug. I blame the wrong wires.

**Comment by Prometheus0000** [comment]
It's good you got it working, but in the future please remember that github is for bug reports, not help getting your machine to work, use the #help channel for that.
